### ISSUE TITLE
Remove default field “doc” that gets added by Couchbase while doing XDCR 

### ISSUE THREAD

**Issue by esnosek** [couchbase/couchbase-elasticsearch-connector#113]
Hello,

This is a feature request to be able to remove "doc" field which gets added on top of original document by Couchbase while doing XDCR. The issue is fully described here:

https://forums.couchbase.com/t/remove-default-field-doc-that-gets-added-by-couchbase-while-doing-xdcr/5328

**Comment by miridfd** [comment]
+1

**Comment by chenbekor** [comment]
+1

**Comment by igorekpotworek** [comment]
+1

**Comment by bertrandgressier** [comment]
+1

**Comment by Branor** [comment]
The problem with removing the 'doc' wrapper is that there is metadata that comes from Couchbase that belongs with the document, and I have to store it with the doc in Elasticsearch. The actual document in ES is:
```
{
"meta": { id, revision, cas, flags},
"doc": { <actual doc> }
}
```

So while I can technically move the doc property up one level, that would effectively make the metadata object a field within the document itself. Which is bad both conceptually - it doesn't belong on the same level of the object hierarchy as the real document properties - and practically - what if your doc already has its own 'meta' property? 

So like I said, it's not hard to do technically, but I don't think it's a good idea. I'm open to changing my mind if you have a good idea on how to implement this without screwing up data integrity.

Storing the metadata separately from the document content is not a good option, because it will remove update atomicity, which in turn leads to data integrity problems. For example, what if the meta and doc parts are stored on separate shards and one of the shards is down?

**Comment by astephensen** [comment]
I'm currently trying to migrate an ancient cluster running Elasticsearch 1.3.7 that uses the river plugin to 2.x that uses the transport plugin. I was hoping for a simple cut-over, though the doc wrapper will require any queries (and code that access the source document) to be modified.

To mitigate some of the issues you described could an additional option be provided to set what property the metadata is stored under? This would allow anyone that have documents with an existing `meta` property to change it to something more specific, e.g. `couchbase_meta`.

**Comment by neverbestboy** [comment]
+1

**Comment by chaddy012** [comment]
+1

**Comment by AzVedi** [comment]
+1

**Comment by dnault** [comment]
Document structure is [now configurable](https://docs.couchbase.com/elasticsearch-connector/4.0/configuration.html#document-structure) in version 4 of the connector.
